#############################################################################
# Makefile for building: template
# Generated by qmake (2.01a) (Qt 4.8.7) on: Fr. Mai 11 10:07:35 2018
# Project:  template.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile template.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-pro

pro//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) pro/ || $(MKDIR) pro/ 
	cd pro/ && $(QMAKE) /home/msoderen/repositories/DrinkRobot/pro/pro.pro -o $(MAKEFILE)
sub-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) pro/ || $(MKDIR) pro/ 
	cd pro/ && $(QMAKE) /home/msoderen/repositories/DrinkRobot/pro/pro.pro -o $(MAKEFILE)
sub-pro: pro//$(MAKEFILE) FORCE
	cd pro/ && $(MAKE) -f $(MAKEFILE)
sub-pro-make_default: pro//$(MAKEFILE) FORCE
	cd pro/ && $(MAKE) -f $(MAKEFILE) 
sub-pro-make_first: pro//$(MAKEFILE) FORCE
	cd pro/ && $(MAKE) -f $(MAKEFILE) first
sub-pro-all: pro//$(MAKEFILE) FORCE
	cd pro/ && $(MAKE) -f $(MAKEFILE) all
sub-pro-clean: pro//$(MAKEFILE) FORCE
	cd pro/ && $(MAKE) -f $(MAKEFILE) clean
sub-pro-distclean: pro//$(MAKEFILE) FORCE
	cd pro/ && $(MAKE) -f $(MAKEFILE) distclean
sub-pro-install_subtargets: pro//$(MAKEFILE) FORCE
	cd pro/ && $(MAKE) -f $(MAKEFILE) install
sub-pro-uninstall_subtargets: pro//$(MAKEFILE) FORCE
	cd pro/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: template.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile template.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile template.pro

qmake_all: sub-pro-qmake_all FORCE

make_default: sub-pro-make_default FORCE
make_first: sub-pro-make_first FORCE
all: sub-pro-all FORCE
clean: sub-pro-clean FORCE
distclean: sub-pro-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-pro-install_subtargets FORCE
uninstall_subtargets: sub-pro-uninstall_subtargets FORCE

sub-pro-check: pro/$(MAKEFILE)
	cd pro/ && $(MAKE) -f $(MAKEFILE) check
check: sub-pro-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

